_wandb:
    value:
        cli_version: 0.22.2
        e:
            e4tp97568a6xwq3zjlstmevpyz7c2odm:
                codePath: src\train.py
                codePathLocal: src\train.py
                cpu_count: 2
                cpu_count_logical: 4
                disk:
                    /:
                        total: "345418444800"
                        used: "114831142912"
                email: rajaramiz.raees1@gmail.com
                executable: C:\Users\Rameez Raja\Downloads\mlops-capstone\.venv\Scripts\python.exe
                host: DESKTOP-90G5JM7
                memory:
                    total: "16810217472"
                os: Windows-10-10.0.19045-SP0
                program: C:\Users\Rameez Raja\Downloads\mlops-capstone\src\train.py
                python: CPython 3.13.7
                root: C:\Users\Rameez Raja\Downloads\mlops-capstone
                startedAt: "2025-10-15T09:19:51.127210Z"
                writerId: e4tp97568a6xwq3zjlstmevpyz7c2odm
        m: []
        python_version: 3.13.7
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 2
                - 16
            "4": 3.13.7
            "5": 0.22.2
            "8":
                - 3
            "12": 0.22.2
            "13": windows-amd64
max_depth:
    value: 7
n_estimators:
    value: 100
